SENT_IMAGE_DETECTOR_DELIMITER = "---"

PROVINCE_CODE_DICT = {
    "aceh": "BL",
    "sumateraUtara": "BB",
    "sumateraBarat": "BA",
    "riau": "BM",
    "jambi": "BH",
    "bengkulu": "BD",
    "sumateraSelatan": "BG",
    "kepulauanBangka": "BN",
    "lampung": "BE",
    "banten": "A",
    "jakarta": "B",
    "jawaBarat": "D",
    "jawaTengah": "H",
    "yogyakarta": "AB",
    "jawaTimur": "N",
    "bali": "DK",
    "nusaTenggaraBarat": "EA",
    "nusaTenggaraTimur": "EB",
    "kalimantanBarat": "KB",
    "kalimantanTengah": "KH",
    "kalimantanSelatan": "DA",
    "kalimantanTimur": "KT",
    "sulawesiUtara": "DB",
    "sulawesiTengah": "DN",
    "sulawesiSelatan": "DD",
    "sulawesiTenggara": "DT",
    "gorontalo": "DM",
    "maluku": "DE",
    "malukuUtara": "DG",
    "papuaBarat": "PB",
    "papua": "PA",
}
