# BASE
BASE_DIR = "src"

# IMAGE
BASE_IMAGE_DIR = f"{BASE_DIR}/images"

ROAD_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/road"
DETECTION_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/detection" # Path untuk mobil
CAR_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/car"
FRAME_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/frame"
TEMPORARY_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/temp"

IMAGE_FOLDER_DICT = {
  'road': ROAD_IMAGE_FOLDER,
  'detection':DETECTION_IMAGE_FOLDER,
  'car':CAR_IMAGE_FOLDER,
  'frame':FRAME_IMAGE_FOLDER,
  'temporary':TEMPORARY_IMAGE_FOLDER,
}

# MODEL
BASE_MODEL_DIR = f"{BASE_DIR}/models"

CAR_MODEL_PATH = f"{BASE_MODEL_DIR}/car_detection_model.pt"
LICENSE_PLATE_MODEL_PATH = f"{BASE_MODEL_DIR}/license_plate_detection_model.pt"



def get_folder_list():
  return [ROAD_IMAGE_FOLDER, DETECTION_IMAGE_FOLDER, TEMPORARY_IMAGE_FOLDER, CAR_IMAGE_FOLDER, FRAME_IMAGE_FOLDER]