# IMAGE
BASE_IMAGE_DIR = "images"

ROAD_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/road"
DETECTION_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/detection" # Path untuk mobil
PLATE_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/plate"
FRAME_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/frame"
TEMPORARY_IMAGE_FOLDER = f"{BASE_IMAGE_DIR}/temp"

IMAGE_FOLDER_DICT = {
  'road': ROAD_IMAGE_FOLDER,
  'detection':DETECTION_IMAGE_FOLDER,
  'plate':PLATE_IMAGE_FOLDER,
  'frame':FRAME_IMAGE_FOLDER,
  'temporary':TEMPORARY_IMAGE_FOLDER,
}

def get_folder_list():
  return [ROAD_IMAGE_FOLDER, DETECTION_IMAGE_FOLDER, TEMPORARY_IMAGE_FOLDER, PLATE_IMAGE_FOLDER, FRAME_IMAGE_FOLDER]